name: loki_psu
description: Loki PSU Mobile App - BLE interface for APW3 V1 power supply unit.
publish_to: 'none'
version: 1.0.0+13

environment:
  sdk: ^3.5.0

dependencies:
  cryptography: ^2.9.0
  flutter:
    sdk: flutter
  flutter_blue_plus: 2.1.0
  flutter_secure_storage: ^10.0.0
  flutter_web_auth_2: ^4.0.0
  http: ^1.6.0
  provider: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
